#2.配置相关信息
spring:
  main:
    banner-mode: off # 关闭SpringBoot启动图标(banner)
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tbl_md?serverTimezone=UTC&useSSL=false #..........................记得改
    username: root
    password: Qq289848
  profiles:
    active: pro
  devtools:
    restart:
      enabled: false #..........................记得改
  cache: #开启缓存
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
server:
  port: 80
#设置Mp相关的配置
mybatis-plus:
  global-config:
    banner: off # 关闭mybatisplus启动图标
#    db-config:
#      table-prefix: tbl_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL日志到控制台


---
#开发
spring:
  profiles: dev
server:
  port: 81
---
#生产
spring:
  profiles: pro
server:
  port: 7999 #..........................记得改
---
#测试
spring:
  profiles: test
server:
  port: 82
---