#2.配置相关信息
spring:
  main:
    banner-mode: off # 关闭SpringBoot启动图标(banner)
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tbl_md?serverTimezone=UTC&useSSL=false #..........................记得改mysql://mysql:3306/tbl_md?serverTimezone=UTC&useSSL=false
    username: root
    password: Qq289848
  profiles:
    active: pro
  devtools:
    restart:
      enabled: false #..........................记得改
  cache: #开启缓存
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
  application:
    name: mywebhou
  cloud:
    nacos:
      server-addr: http://192.168.0.172:8848 #      server-addr: nacos:8848 # nacos地址
      config:
        file-extension: yml # 文件后缀名
        enabled: true
#设置Mp相关的配置
mybatis-plus:
  global-config:
    banner: off # 关闭mybatisplus启动图标




---
#开发
spring:
  profiles: dev
server:
  port: 81
---
#生产
spring:
  profiles: pro
server:
  port: 7998 #..........................记得改
---
#测试
spring:
  profiles: test
server:
  port: 82
---